(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const STORE_URL = 'https://play.google.com/store/apps/details?id=com.extrude.studio.office.flip';
  const state = {phase:'brief', cleaned:0, placed:0, dragging:null, selectedChair:null, chairRotated:false};
  const refs = {brief:$('#brief'),done:$('#done'),cleanHud:$('#cleanHud'),catalog:$('#catalog'),cleanCount:$('#cleanCount'),placeCount:$('#placeCount'),stepLabel:$('#stepLabel'),stepCount:$('#stepCount'),reaction:$('#mayaReaction'),reactionText:$('#reactionText'),toast:$('#toast'),rotate:$('#rotate'),placed:$('#placed'),room:$('#room')};

  function tone(freq=520,duration=.07){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const c=tone.ctx||(tone.ctx=new AC()),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+duration)}catch(_){}}
  function toast(message){refs.toast.textContent=message;refs.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>refs.toast.classList.remove('show'),1500)}
  function react(message){refs.reactionText.textContent=message;refs.reaction.classList.add('show');clearTimeout(react.timer);react.timer=setTimeout(()=>refs.reaction.classList.remove('show'),2300)}
  function install(){if(window.ExitApi&&typeof window.ExitApi.exit==='function')window.ExitApi.exit();else window.open(STORE_URL,'_blank','noopener')}
  function begin(){state.phase='clean';refs.brief.classList.remove('show');refs.cleanHud.classList.remove('hidden');refs.stepLabel.textContent='PREPARE THE ROOM';refs.stepCount.textContent='1 / 3';tone(460);toast('Tap each mess to clear it')}
  function clearMess(button){if(state.phase!=='clean'||button.classList.contains('cleared'))return;button.classList.add('cleared');state.cleaned++;refs.cleanCount.textContent=`${state.cleaned} / 3`;tone(620+state.cleaned*90);if(state.cleaned===1)react('Yes! I can see the floor again.');if(state.cleaned===3)setTimeout(startFurnish,500)}
  function startFurnish(){state.phase='furnish';refs.cleanHud.classList.add('hidden');refs.catalog.classList.remove('hidden');$$('.dropzone').forEach(z=>z.classList.add('active'));refs.stepLabel.textContent='FURNISH THE OFFICE';refs.stepCount.textContent='2 / 3';toast('Drag each item into its matching outline')}
  function point(e){const p=e.changedTouches?.[0]||e.touches?.[0]||e;return{x:p.clientX,y:p.clientY}}
  function beginDrag(e,item){if(state.phase!=='furnish'||item.classList.contains('placed'))return;e.preventDefault();const kind=item.dataset.kind,ghost=document.createElement('img');ghost.src=item.querySelector('img').src;ghost.className='drag-ghost';ghost.dataset.kind=kind;document.body.appendChild(ghost);state.dragging={item,ghost,kind};moveDrag(e);tone(390);$$('.dropzone').forEach(z=>z.classList.toggle('good',z.dataset.kind===kind))}
  function moveDrag(e){if(!state.dragging)return;e.preventDefault();const p=point(e);state.dragging.ghost.style.left=`${p.x}px`;state.dragging.ghost.style.top=`${p.y}px`}
  function endDrag(e){if(!state.dragging)return;e.preventDefault();const p=point(e),zone=$(`.dropzone[data-kind="${state.dragging.kind}"]`),r=zone.getBoundingClientRect(),valid=p.x>=r.left&&p.x<=r.right&&p.y>=r.top&&p.y<=r.bottom;if(valid)placeItem(zone);else{zone.classList.add('bad');toast('Try the matching green outline');tone(180,.12);setTimeout(()=>zone.classList.remove('bad'),500)}state.dragging.ghost.remove();$$('.dropzone').forEach(z=>z.classList.remove('good'));state.dragging=null}
  function placeItem(zone){const kind=state.dragging.kind,rect=zone.getBoundingClientRect(),stageRect=$('#stage').getBoundingClientRect(),img=document.createElement('img');img.src=state.dragging.ghost.src;img.className=`placed-item ${kind}`;img.style.left=`${rect.left-stageRect.left+rect.width/2}px`;img.style.top=`${rect.top-stageRect.top+rect.height/2}px`;refs.placed.appendChild(img);state.dragging.item.classList.add('placed');zone.classList.remove('active');state.placed++;refs.placeCount.textContent=`${state.placed} / 3`;tone(760);if(kind==='chair'){state.selectedChair=img;refs.rotate.classList.remove('hidden');toast('Nice—rotate the chair toward the desk')}else react(kind==='desk'?'Now I have somewhere to create.':'That plant makes the room feel alive!');checkComplete()}
  function rotateChair(){if(!state.selectedChair||state.chairRotated)return;state.chairRotated=true;state.selectedChair.classList.add('rotated');refs.rotate.classList.add('hidden');tone(820);react('Perfect angle. I am ready to work!');checkComplete()}
  function checkComplete(){if(state.placed===3&&state.chairRotated){state.phase='done';refs.stepLabel.textContent='CONTRACT COMPLETE';refs.stepCount.textContent='3 / 3';setTimeout(()=>{refs.catalog.classList.add('hidden');refs.reaction.classList.remove('show');refs.done.classList.add('show');refs.room.src='../../assets/screenshots/office-flip/gameplay-02.webp';tone(980,.16)},800)}}
  function reset(){state.phase='clean';state.cleaned=0;state.placed=0;state.dragging=null;state.selectedChair=null;state.chairRotated=false;refs.done.classList.remove('show');refs.cleanHud.classList.remove('hidden');refs.catalog.classList.add('hidden');refs.cleanCount.textContent='0 / 3';refs.placeCount.textContent='0 / 3';refs.stepLabel.textContent='PREPARE THE ROOM';refs.stepCount.textContent='1 / 3';refs.room.src='../../assets/screenshots/office-flip/gameplay-07.webp';refs.placed.innerHTML='';refs.rotate.classList.add('hidden');$$('.clutter').forEach(x=>x.classList.remove('cleared'));$$('.item').forEach(x=>x.classList.remove('placed'));$$('.dropzone').forEach(x=>x.classList.remove('active','good','bad'));tone(440)}

  $('#begin').addEventListener('click',begin);$('#replay').addEventListener('click',reset);$('#install').addEventListener('click',install);$('#footerInstall').addEventListener('click',install);refs.rotate.addEventListener('click',rotateChair);$$('[data-clutter]').forEach(b=>b.addEventListener('click',()=>clearMess(b)));$$('.item').forEach(item=>item.addEventListener('pointerdown',e=>beginDrag(e,item)));window.addEventListener('pointermove',moveDrag,{passive:false});window.addEventListener('pointerup',endDrag,{passive:false});
})();
